/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	healthv1 "github.com/hsiaoairplane/k8s-crd/pkg/apis/health/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHealths implements HealthInterface
type FakeHealths struct {
	Fake *FakeHsiaoairplaneV1
	ns   string
}

var healthsResource = schema.GroupVersionResource{Group: "hsiaoairplane.io", Version: "v1", Resource: "healths"}

var healthsKind = schema.GroupVersionKind{Group: "hsiaoairplane.io", Version: "v1", Kind: "Health"}

// Get takes name of the health, and returns the corresponding health object, and an error if there is any.
func (c *FakeHealths) Get(name string, options v1.GetOptions) (result *healthv1.Health, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(healthsResource, c.ns, name), &healthv1.Health{})

	if obj == nil {
		return nil, err
	}
	return obj.(*healthv1.Health), err
}

// List takes label and field selectors, and returns the list of Healths that match those selectors.
func (c *FakeHealths) List(opts v1.ListOptions) (result *healthv1.HealthList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(healthsResource, healthsKind, c.ns, opts), &healthv1.HealthList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &healthv1.HealthList{ListMeta: obj.(*healthv1.HealthList).ListMeta}
	for _, item := range obj.(*healthv1.HealthList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested healths.
func (c *FakeHealths) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(healthsResource, c.ns, opts))

}

// Create takes the representation of a health and creates it.  Returns the server's representation of the health, and an error, if there is any.
func (c *FakeHealths) Create(health *healthv1.Health) (result *healthv1.Health, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(healthsResource, c.ns, health), &healthv1.Health{})

	if obj == nil {
		return nil, err
	}
	return obj.(*healthv1.Health), err
}

// Update takes the representation of a health and updates it. Returns the server's representation of the health, and an error, if there is any.
func (c *FakeHealths) Update(health *healthv1.Health) (result *healthv1.Health, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(healthsResource, c.ns, health), &healthv1.Health{})

	if obj == nil {
		return nil, err
	}
	return obj.(*healthv1.Health), err
}

// Delete takes name of the health and deletes it. Returns an error if one occurs.
func (c *FakeHealths) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(healthsResource, c.ns, name), &healthv1.Health{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHealths) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(healthsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &healthv1.HealthList{})
	return err
}

// Patch applies the patch and returns the patched health.
func (c *FakeHealths) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *healthv1.Health, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(healthsResource, c.ns, name, pt, data, subresources...), &healthv1.Health{})

	if obj == nil {
		return nil, err
	}
	return obj.(*healthv1.Health), err
}
